# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-websocket'
gem 'em-websocket'
gem 'em-websocket-client'
gem 'mongo'
gem 'json'
gem 'slim'
gem 'empezar'
gem 'pry'
gem 'better_errors'
gem 'haml'
gem 'sass'
gem 'fetcher-mongoid-models'