# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'sinatra-websocket'
gem 'em-websocket'
gem 'em-websocket-client'
gem 'omniauth-twitter'
gem 'twitter'
gem 'pry'
gem 'haml'
gem 'sass'
gem 'binding_of_caller'
gem 'better_errors'
gem 'symbolmatrix'
gem 'mongo'
gem 'koala'
gem 'fetcher-mongoid-models'
